### ISSUE TITLE
Error while running test.sh in kgat folder

### ISSUE THREAD

**Issue by ishikasingh** [thunlp/KernelGAT#8]
Traceback (most recent call last):
  File "test.py", line 85, in <module>
    model.load_state_dict(torch.load(args.checkpoint)['model'])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 771, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for inference_model:
        Missing key(s) in state_dict: "proj_inference_de.weight", "proj_inference_de.bias", "proj_att.weight", "proj_att.bias", "proj_input_de.weight", "proj_input_de.bias", "proj_gat.0.weight", "proj_gat.0.bias", "proj_gat.2.weight", "proj_gat.2.bias", "proj_select.weight", "proj_select.bias".
        Unexpected key(s) in state_dict: "proj_match.weight", "proj_match.bias".

**Comment by EdwardZH** [comment]
Please use the new version of our codes, we have fixed it.

**Comment by ishikasingh** [comment]
Can you also provide the version of dependencies to use? I'm getting another error:

Traceback (most recent call last):
  File "test.py", line 81, in <module>
    bert_model = BertForSequenceEncoder.from_pretrained(args.bert_pretrain)
  File "/home/code-base/KernelGAT/kgat/bert_model.py", line 581, in from_pretrained
    model = cls(config, *inputs, **kwargs)
  File "/home/code-base/KernelGAT/kgat/bert_model.py", line 765, in __init__
    self.bert = BertModel(config)
  File "/home/code-base/KernelGAT/kgat/bert_model.py", line 685, in __init__
    self.embeddings = BertEmbeddings(config)
  File "/home/code-base/KernelGAT/kgat/bert_model.py", line 247, in __init__
    self.LayerNorm = BertLayerNorm(config.hidden_size, eps=1e-12)
  File "/opt/conda/lib/python3.6/site-packages/apex/normalization/fused_layer_norm.py", line 126, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /opt/conda/lib/python3.6/site-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeERKNS_6TensorE

**Comment by EdwardZH** [comment]
Please refer to hugginface bug solution and change the cuda version. https://github.com/huggingface/transformers/issues/1093. In addition, you can update the version of hugginface's transformers easily.

**Comment by ishikasingh** [comment]
Thanks for suggesting, I actually did that but it worked when I downgraded to PyTorch 1.3!
